package com.sharefable.api.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.sharefable.api.entity.CreationMutationReceipt;
import com.sharefable.api.entity.User;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.function.Supplier;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

/** Durable acknowledgement for a single existing creation mutation, not an aggregate transaction. */
@Service
@RequiredArgsConstructor
public class CreationMutationService {
  private final ObjectMapper mapper;
  @PersistenceContext
  private EntityManager entityManager;

  @Transactional
  public <T> T execute(String key, String operation, User user, Object request, Class<T> responseType, Supplier<T> mutation) {
    if (key == null) return mutation.get();
    if (!key.matches("[A-Za-z0-9_:/.-]{1,160}")) {
      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Invalid creation retry key");
    }
    if (user.getBelongsToOrg() == null || !user.hasActiveMembership(user.getBelongsToOrg())) {
      throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Active workspace membership required");
    }
    String scopedKey = hash(user.getId() + ":" + user.getBelongsToOrg() + ":" + operation + ":" + key);
    try {
      String requestHash = hash(mapper.writeValueAsString(request));
      // A unique-key upsert locks existing receipts too. Concurrent retries wait
      // for the first transaction to commit or roll back before inspecting it.
      entityManager.createNativeQuery("INSERT INTO creation_mutation_receipt (key_hash, request_hash) "
          + "VALUES (:key, :request) ON DUPLICATE KEY UPDATE key_hash = key_hash")
        .setParameter("key", scopedKey).setParameter("request", requestHash).executeUpdate();
      CreationMutationReceipt receipt = entityManager.find(CreationMutationReceipt.class, scopedKey);
      if (!requestHash.equals(receipt.getRequestHash())) {
        throw new ResponseStatusException(HttpStatus.CONFLICT, "This creation retry differs from the original request");
      }
      if (receipt.getResponseJson() != null) return mapper.readValue(receipt.getResponseJson(), responseType);
      T response = mutation.get();
      ObjectNode serialized = mapper.valueToTree(response);
      // Expiring upload credentials are regenerated by the screen endpoint.
      serialized.remove("uploadUrl");
      receipt.setResponseJson(mapper.writeValueAsString(serialized));
      entityManager.flush();
      return response;
    } catch (JsonProcessingException error) {
      throw new IllegalStateException("Creation acknowledgement could not be stored", error);
    }
  }

  private static String hash(String value) {
    try {
      return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));
    } catch (NoSuchAlgorithmException error) {
      throw new IllegalStateException(error);
    }
  }
}
